# Document Generation Endpoints

generate-document:
  post:
    operationId: generateDocument
    summary: Generate a single document asynchronously
    description: Submit a request to generate a single PDF document. Returns immediately with a job ID for tracking progress.
    tags:
      - Generation
    parameters:
      - name: tenantId
        in: path
        required: true
        description: Tenant identifier
        schema:
          type: integer
          format: int64
    requestBody:
      required: true
      content:
        application/vnd.epistola.v1+json:
          schema:
            $ref: '../components/schemas/generation.yaml#/GenerateDocumentRequest'
    responses:
      '202':
        description: Generation request accepted
        content:
          application/vnd.epistola.v1+json:
            schema:
              $ref: '../components/schemas/generation.yaml#/GenerationJobResponse'
      '400':
        description: Invalid request
        content:
          application/vnd.epistola.v1+json:
            schema:
              $ref: '../components/responses/errors.yaml#/ValidationErrorResponse'

generate-batch:
  post:
    operationId: generateDocumentBatch
    summary: Generate multiple documents in a batch
    description: Submit a batch request to generate multiple PDF documents. Returns immediately with a job ID for tracking progress.
    tags:
      - Generation
    parameters:
      - name: tenantId
        in: path
        required: true
        description: Tenant identifier
        schema:
          type: integer
          format: int64
    requestBody:
      required: true
      content:
        application/vnd.epistola.v1+json:
          schema:
            $ref: '../components/schemas/generation.yaml#/GenerateBatchRequest'
    responses:
      '202':
        description: Batch generation request accepted
        content:
          application/vnd.epistola.v1+json:
            schema:
              $ref: '../components/schemas/generation.yaml#/GenerationJobResponse'
      '400':
        description: Invalid request
        content:
          application/vnd.epistola.v1+json:
            schema:
              $ref: '../components/responses/errors.yaml#/ValidationErrorResponse'

jobs:
  get:
    operationId: listGenerationJobs
    summary: List generation jobs
    description: List all generation jobs for a tenant with optional status filtering
    tags:
      - Generation
    parameters:
      - name: tenantId
        in: path
        required: true
        description: Tenant identifier
        schema:
          type: integer
          format: int64
      - name: status
        in: query
        description: Filter by job status
        schema:
          type: string
          enum: [PENDING, IN_PROGRESS, COMPLETED, FAILED, CANCELLED]
      - name: page
        in: query
        description: Page number (0-based)
        schema:
          type: integer
          default: 0
          minimum: 0
      - name: size
        in: query
        description: Number of items per page
        schema:
          type: integer
          default: 20
          minimum: 1
          maximum: 100
    responses:
      '200':
        description: List of generation jobs
        content:
          application/vnd.epistola.v1+json:
            schema:
              $ref: '../components/schemas/generation.yaml#/GenerationJobListResponse'

job-detail:
  parameters:
    - name: tenantId
      in: path
      required: true
      description: Tenant identifier
      schema:
        type: integer
        format: int64
    - name: requestId
      in: path
      required: true
      description: Generation request ID
      schema:
        type: string
        format: uuid

  get:
    operationId: getGenerationJobStatus
    summary: Get generation job status
    description: Get detailed status of a generation job including all items and their progress
    tags:
      - Generation
    responses:
      '200':
        description: Job status with items
        content:
          application/vnd.epistola.v1+json:
            schema:
              $ref: '../components/schemas/generation.yaml#/GenerationJobDetail'
      '404':
        description: Job not found
        content:
          application/vnd.epistola.v1+json:
            schema:
              $ref: '../components/responses/errors.yaml#/ValidationErrorResponse'

  delete:
    operationId: cancelGenerationJob
    summary: Cancel a generation job
    description: Cancel a pending or in-progress generation job
    tags:
      - Generation
    responses:
      '204':
        description: Job cancelled successfully
      '404':
        description: Job not found
      '409':
        description: Job cannot be cancelled (already completed, failed, or cancelled)

documents:
  get:
    operationId: listDocuments
    summary: List generated documents
    description: List all generated documents for a tenant with optional filtering
    tags:
      - Generation
    parameters:
      - name: tenantId
        in: path
        required: true
        description: Tenant identifier
        schema:
          type: integer
          format: int64
      - name: templateId
        in: query
        description: Filter by template ID
        schema:
          type: integer
          format: int64
      - name: correlationId
        in: query
        description: Filter by client-provided correlation ID
        schema:
          type: string
          maxLength: 255
      - name: page
        in: query
        description: Page number (0-based)
        schema:
          type: integer
          default: 0
          minimum: 0
      - name: size
        in: query
        description: Number of items per page
        schema:
          type: integer
          default: 20
          minimum: 1
          maximum: 100
    responses:
      '200':
        description: List of documents
        content:
          application/vnd.epistola.v1+json:
            schema:
              $ref: '../components/schemas/generation.yaml#/DocumentListResponse'

document-detail:
  parameters:
    - name: tenantId
      in: path
      required: true
      description: Tenant identifier
      schema:
        type: integer
        format: int64
    - name: documentId
      in: path
      required: true
      description: Document ID
      schema:
        type: integer
        format: int64

  get:
    operationId: downloadDocument
    summary: Download a generated document
    description: Download the PDF content of a generated document
    tags:
      - Generation
    responses:
      '200':
        description: Document content
        content:
          application/pdf:
            schema:
              type: string
              format: binary
        headers:
          Content-Disposition:
            schema:
              type: string
            description: Attachment filename
          Content-Length:
            schema:
              type: integer
            description: File size in bytes
      '404':
        description: Document not found

  delete:
    operationId: deleteDocument
    summary: Delete a generated document
    description: Permanently delete a generated document
    tags:
      - Generation
    responses:
      '204':
        description: Document deleted successfully
      '404':
        description: Document not found
