/*
 * Theme.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * Generated from JSON Schema &mdash; do not edit manually
 */
package app.epistola.template.model

import java.math.BigDecimal

/**
 * Theme definition providing default styles, page settings, and named block style presets.
 */
data class Theme(
    /** Theme identifier (slug format). */
    val id: String,
    /** Human-readable theme name. */
    val name: String,
    /** Default document-level styles inherited by all templates using this theme. */
    val documentStyles: DocumentStyles? = null,
    /** Default page settings inherited by templates using this theme. */
    val pageSettings: PageSettings? = null,
    /** Named block style presets (like CSS classes). Key is the preset name. */
    val blockStylePresets: BlockStylePresets? = null,
    /** Base spacing unit in points for the spacing scale. All sp values (e.g. 2sp, 4sp) are multiples of this value. Absent means default (4pt). */
    val spacingUnit: BigDecimal? = null
) {

    init {
        require(id.isNotEmpty()) { "id length < minimum 1 - ${id.length}" }
        require(name.isNotEmpty()) { "name length < minimum 1 - ${name.length}" }
        if (spacingUnit != null)
            require(spacingUnit in cg_dec0..cg_dec1) { "spacingUnit not in range 1..16 - $spacingUnit" }
    }

    /**
     * Named block style presets (like CSS classes). Key is the preset name.
     */
    open class BlockStylePresets

    companion object {
        private val cg_dec0 = BigDecimal.ONE
        private val cg_dec1 = BigDecimal("16")
    }

}
