# GitHub Labels Configuration
# This file is the source of truth for repository labels.
# Labels are automatically synced via .github/workflows/labels.yml
#
# Color reference (no # prefix):
#   Red shades:    d73a4a, b60205, e99695
#   Orange shades: f9a825, d93f0b, fbca04
#   Yellow shades: fef2c0, f9d0c4
#   Green shades:  0e8a16, 28a745, 7ee787
#   Blue shades:   0075ca, 1d76db, 0366d6, 00bcd4
#   Purple shades: 7057ff, 5319e7, d876e3
#   Gray shades:   cccccc, 666666, ededed

# Issue Type Labels
- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: feature
  color: "28a745"
  description: New feature request

- name: documentation
  color: "0075ca"
  description: Documentation improvements

- name: question
  color: "d876e3"
  description: Further information is requested

# Priority Labels
- name: "priority: critical"
  color: "b60205"
  description: Must be fixed ASAP

- name: "priority: high"
  color: "d93f0b"
  description: High priority issue

- name: "priority: low"
  color: "fef2c0"
  description: Low priority issue

# Status Labels
- name: "status: blocked"
  color: "d73a4a"
  description: Blocked by another issue or external factor

- name: "status: in progress"
  color: "fbca04"
  description: Currently being worked on

- name: "status: needs review"
  color: "1d76db"
  description: Needs code review

- name: "status: needs triage"
  color: "ededed"
  description: Needs initial assessment

# Component Labels
- name: backend
  color: "f9a825"
  description: Kotlin/Spring Boot related

- name: frontend
  color: "00bcd4"
  description: Thymeleaf/HTMX/UI related

- name: infrastructure
  color: "666666"
  description: CI/CD, Docker, deployment

# Contributor Labels
- name: "good first issue"
  color: "7057ff"
  description: Good for newcomers

- name: "help wanted"
  color: "0e8a16"
  description: Extra attention needed

# Resolution Labels
- name: duplicate
  color: "cccccc"
  description: This issue or pull request already exists

- name: invalid
  color: "e4e669"
  description: This doesn't seem right

- name: wontfix
  color: "ffffff"
  description: This will not be worked on

# CI/CD Labels
- name: publish
  color: "5319e7"
  description: Triggers Docker image build for PR (used by CI)

# Breaking Changes
- name: "breaking change"
  color: "b60205"
  description: Introduces breaking changes

# Domain Labels (for backlog organization)
- name: "domain: api"
  color: "0075ca"
  description: REST API, OpenAPI, contracts

- name: "domain: editor"
  color: "00bcd4"
  description: Template editor features

- name: "domain: generation"
  color: "28a745"
  description: Document rendering (HTML/PDF)

- name: "domain: sdk"
  color: "7057ff"
  description: Client SDK development

- name: "domain: security"
  color: "b60205"
  description: Auth, authorization, API keys

- name: "domain: operations"
  color: "f9a825"
  description: Metrics, monitoring, storage

- name: "domain: governance"
  color: "5319e7"
  description: Lifecycle, versioning, environments

- name: "domain: theming"
  color: "d876e3"
  description: Styling, themes, branding

- name: "domain: assets"
  color: "666666"
  description: Image/file management

- name: "domain: docs"
  color: "0366d6"
  description: Product documentation

- name: "domain: integrations"
  color: "1d76db"
  description: External system connections

# Phase Labels
- name: "phase: mvp"
  color: "b60205"
  description: Must have for initial release

- name: "phase: adoption"
  color: "d93f0b"
  description: Important for broader adoption

- name: "phase: enterprise"
  color: "fbca04"
  description: Enterprise features

- name: "phase: later"
  color: "fef2c0"
  description: Future consideration

# Size Labels
- name: "size: xs"
  color: "ededed"
  description: Less than 1 day

- name: "size: s"
  color: "cccccc"
  description: 1-2 days

- name: "size: m"
  color: "999999"
  description: 3-5 days

- name: "size: l"
  color: "666666"
  description: 1-2 weeks

- name: "size: xl"
  color: "333333"
  description: More than 2 weeks
