# SPDX-FileCopyrightText: Epistola Nederland B.V.
#
# SPDX-License-Identifier: AGPL-3.0-only

packages:
  - modules/*
  - scripts/gh-mcp
  - .husky
onlyBuiltDependencies:
  - core-js
  - esbuild
  - keytar
  - protobufjs
