name: Documentation
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Type of Documentation Issue
      options:
        - Missing documentation
        - Unclear or confusing
        - Incorrect or outdated
        - Typo or grammar
        - Suggestion for improvement
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation that needs improvement?
      placeholder: |
        - README.md, section "Getting Started"
        - Code comments in src/main/kotlin/...
        - API documentation
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current State
      description: What does the documentation currently say (or what's missing)?
    validations:
      required: true

  - type: textarea
    id: desired
    attributes:
      label: Desired State
      description: What should the documentation say instead?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context that might be helpful.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
