# SPDX-FileCopyrightText: Epistola Nederland B.V.
#
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: v1
kind: Service
metadata:
  name: {{ include "epistola.fullname" . }}
  labels:
    {{- include "epistola.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "epistola.selectorLabels" . | nindent 4 }}
