package app.epistola.suite.mcp

import app.epistola.suite.mcp.dto.ApplicableStyles
import app.epistola.suite.mcp.tools.ComponentMcpTools
import app.epistola.suite.testing.IntegrationTestBase
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired

/**
 * Verifies that the editor's TypeScript component registry is exposed through
 * the MCP `list_component_types` / `get_component_type` tools. The JSON file
 * is generated by `pnpm --filter @epistola/editor dump-registry` and shipped
 * in the editor module's resources.
 */
class ComponentTypesIntegrationTest : IntegrationTestBase() {

    @Autowired
    private lateinit var componentTools: ComponentMcpTools

    @Test
    fun `list_component_types exposes the editor's component types`() {
        val components = componentTools.listComponentTypes()

        // The current TS registry has 16 components. Asserting on the count
        // would be flaky as the registry evolves; assert on the core types
        // every template needs.
        assertThat(components).isNotEmpty
        val types = components.map { it.type }.toSet()
        assertThat(types).contains(
            "root",
            "text",
            "container",
            "columns",
            "table",
            "datatable",
            "qrcode",
            "conditional",
            "loop",
            "datalist",
            "separator",
            "pagebreak",
            "pageheader",
            "pagefooter",
        )
    }

    @Test
    fun `text component descriptor carries the expected fields`() {
        val text = componentTools.getComponentType("text")
        assertThat(text).isNotNull
        assertThat(text!!.label).isEqualTo("Text")
        assertThat(text.category).isEqualTo("content")
        assertThat(text.hidden).isFalse
        assertThat(text.slots).isEmpty()
        // text has no children
        assertThat(text.allowedChildren.mode).isEqualTo("none")
        // text supports all style keys
        assertThat(text.applicableStyles).isInstanceOf(ApplicableStyles.All::class.java)
    }

    @Test
    fun `container allows any child type`() {
        val container = componentTools.getComponentType("container")
        assertThat(container).isNotNull
        assertThat(container!!.allowedChildren.mode).isEqualTo("all")
        assertThat(container.slots).hasSize(1)
        assertThat(container.slots[0].name).isEqualTo("children")
    }

    @Test
    fun `pageheader is a singleton page block`() {
        val pageHeader = componentTools.getComponentType("pageheader")
        assertThat(pageHeader).isNotNull
        assertThat(pageHeader!!.category).isEqualTo("page")
        assertThat(pageHeader.maxInstancesPerDocument).isEqualTo(1)
    }

    @Test
    fun `datatable-column is hidden so it doesn't appear in the palette`() {
        val column = componentTools.getComponentType("datatable-column")
        assertThat(column).isNotNull
        assertThat(column!!.hidden).isTrue
    }

    @Test
    fun `get_component_type returns null for an unknown type`() {
        assertThat(componentTools.getComponentType("does-not-exist")).isNull()
    }
}
