package app.epistola.suite.mcp

import app.epistola.suite.mcp.dto.ApplicableStyles
import app.epistola.suite.mcp.tools.ComponentMcpTools
import app.epistola.suite.testing.IntegrationTestBase
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired

/**
 * Verifies that the editor's TypeScript component registry is exposed through
 * the MCP `list_component_types` / `get_component_type` tools. The JSON file
 * is generated by `pnpm --filter @epistola/editor dump-registry` and shipped
 * in the editor module's resources.
 */
class ComponentTypesIntegrationTest : IntegrationTestBase() {

    @Autowired
    private lateinit var componentTools: ComponentMcpTools

    @Test
    fun `list_component_types exposes the editor's component types`() {
        val components = componentTools.listComponentTypes()

        // The current TS registry has 16 components. Asserting on the count
        // would be flaky as the registry evolves; assert on the core types
        // every template needs.
        assertThat(components).isNotEmpty
        val types = components.map { it.type }.toSet()
        assertThat(types).contains(
            "root",
            "text",
            "container",
            "columns",
            "table",
            "datatable",
            "qrcode",
            "conditional",
            "loop",
            "datalist",
            "separator",
            "pagebreak",
            "pageheader",
            "pagefooter",
        )
    }

    @Test
    fun `text component descriptor carries the expected fields`() {
        val text = componentTools.getComponentType("text")
        assertThat(text).isNotNull
        assertThat(text!!.label).isEqualTo("Text")
        assertThat(text.category).isEqualTo("content")
        assertThat(text.hidden).isFalse
        assertThat(text.slots).isEmpty()
        // text has no children
        assertThat(text.allowedChildren.mode).isEqualTo("none")
        // text supports all style keys
        assertThat(text.applicableStyles).isInstanceOf(ApplicableStyles.All::class.java)
    }

    @Test
    fun `container allows any child type`() {
        val container = componentTools.getComponentType("container")
        assertThat(container).isNotNull
        assertThat(container!!.allowedChildren.mode).isEqualTo("all")
        assertThat(container.slots).hasSize(1)
        assertThat(container.slots[0].name).isEqualTo("children")
    }

    @Test
    fun `pageheader is a singleton page block`() {
        val pageHeader = componentTools.getComponentType("pageheader")
        assertThat(pageHeader).isNotNull
        assertThat(pageHeader!!.category).isEqualTo("page")
        assertThat(pageHeader.maxInstancesPerDocument).isEqualTo(1)
    }

    @Test
    fun `datatable-column is hidden so it doesn't appear in the palette`() {
        val column = componentTools.getComponentType("datatable-column")
        assertThat(column).isNotNull
        assertThat(column!!.hidden).isTrue
    }

    @Test
    fun `get_component_type returns null for an unknown type`() {
        assertThat(componentTools.getComponentType("does-not-exist")).isNull()
    }

    @Test
    fun `every user-insertable component carries at least one example`() {
        // Every component an AI client can insert should ship a usage example so
        // the AI doesn't have to invent the JSON shape. Root is implicit (the
        // document already has it); hidden components are child-only and not
        // directly insertable, but datatable-column is documented so the AI
        // can compose datatables.
        val skipped = setOf("root")
        val missing = componentTools.listComponentTypes()
            .filter { it.type !in skipped }
            .filter { it.examples.isEmpty() }
            .map { it.type }
        assertThat(missing).isEmpty()
    }

    @Test
    fun `each example's root node is present in fragment nodes and has the matching type`() {
        // Sanity check: every example's rootNodeId must appear in its nodes map
        // and the node found there must have the same type as the parent component.
        // Catches authoring mistakes (mistyped IDs, copy-paste between types).
        val mismatches = mutableListOf<String>()
        for (component in componentTools.listComponentTypes()) {
            for (example in component.examples) {
                val rootNode = example.fragment.nodes[example.fragment.rootNodeId]
                if (rootNode == null) {
                    mismatches += "${component.type}/${example.name}: rootNodeId '${example.fragment.rootNodeId}' not in nodes"
                    continue
                }
                val nodeType = rootNode["type"] as? String
                if (nodeType != component.type) {
                    mismatches += "${component.type}/${example.name}: root node has type '$nodeType', expected '${component.type}'"
                }
            }
        }
        assertThat(mismatches).isEmpty()
    }

    @Test
    fun `datatable invoice example demonstrates the full iteration pattern`() {
        val datatable = componentTools.getComponentType("datatable")
        assertThat(datatable).isNotNull
        val example = datatable!!.examples.firstOrNull { it.name == "invoice-line-items" }
        assertThat(example).isNotNull
        assertThat(example!!.description).contains("items")
        // The example should have multiple datatable-column children
        val columnNodes = example.fragment.nodes.values.filter { it["type"] == "datatable-column" }
        assertThat(columnNodes).hasSizeGreaterThanOrEqualTo(2)
    }

    @Test
    fun `text example with expression demonstrates inline data binding`() {
        val text = componentTools.getComponentType("text")
        val withExpression = text?.examples?.firstOrNull { it.name == "with-expression" }
        assertThat(withExpression).isNotNull
        // The example's description should mention expressions to help the AI find it
        assertThat(withExpression!!.description.lowercase()).contains("expression")
    }
}
